language: node_js
node_js:
- node
- lts/*
- 10
before_script:
  - "git submodule update --init"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "phantomjs test/phantom-js-loader.js"
